---
- hosts: win
  tasks:
  - name: instaling service in windows
    win_get_url:
      url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
      dest: 'C:\Temp\httpd-2.2.25-win32-x86-no_ssl.msi'
  - name: install the MSI
    win_package:
      path: 'C:\Temp\httpd-2.2.25-win32-x86-no_ssl.msi'
      state: present
  - name: installing Choo
    win_shell: "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
